Fix fs.constants
json-schema-tools/dereferencer pull request #61
Opened 2020-09-02 08:20 UTC by jetexe

Make stub for `fs.constants` for web
Fix: #60

2020-09-08 21:44 UTC, BelfordZ commented on CHANGELOG.md
> +## [Unreleased](https://github.com/json-schema-tools/dereferencer/compare/master...1.2.1)
Changelog gets automatically updated =P

2020-09-08 21:44 UTC, BelfordZ commented
Commits must follow the conventional commit format: https://github.com/json-schema-tools/dereferencer/blob/master/CONVENTIONAL_COMMITS.md

2020-09-08 21:46 UTC, BelfordZ commented
please use 1 commit, with the following: 
```
fix: fs.constants updated for web

resolves #61
```

2020-09-08 21:48 UTC, BelfordZ requested changes
also please rebase, as I've updated some deps.

2020-09-09 05:09 UTC, jetexe commented on CHANGELOG.md
> +## [Unreleased](https://github.com/json-schema-tools/dereferencer/compare/master...1.2.1)
fixed

2020-09-09 05:13 UTC, merged

2020-09-09 05:16 UTC, BelfordZ commented
:tada: This PR is included in version 1.2.2 :tada:

The release is available on:
- [GitHub release](https://github.com/json-schema-tools/dereferencer/releases/tag/1.2.2)
- `1.2.2`
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@json-schema-tools/dereferencer/v/1.2.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: